language: ruby
rvm:
  - 2.4.2
env:
  - DB=postgresql
cache: bundler
addons:
  postgresql: "9.4"
services:
  - postgresql
  - mongodb
  - redis
script:
  - RAILS_ENV=test bundle exec rake teaspoon
  - RAILS_ENV=test xvfb-run -a bundle exec rake parallel:spec
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - cp config/database.travis.yml config/database.yml
  - cp config/mongoid.travis.yml config/mongoid.yml
  - export PARALLEL_TEST_PROCESSORS=4
  - RAILS_ENV=development bundle exec rake db:create db:migrate
  - bundle exec rake parallel:create parallel:load_schema parallel:prepare