# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5925d1f3dd9d8adc946461f0c06bbef6351fc029c61c9678881224d04c898e794ba7f28e47554ec5e69580f7c8ba3b95df29636efde164ab619a22806d0e9bdf

test:
  secret_key_base: 47ebfa289fdd303b7444e81e867e51c3334e4f0b343995931e6134effebd567768db593d604932ebbcc0bd5ccb5776c0a9e1b86860755812193039cec458bb00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
